/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.pharmacy.pharmacymanagementsystem.view;

import com.pharmacy.pharmacymanagementsystem.dao.BillingDAO;
import com.pharmacy.pharmacymanagementsystem.model.Sale;
import com.pharmacy.pharmacymanagementsystem.model.SaleItem;
import com.pharmacy.pharmacymanagementsystem.dao.MedicineDAO;
import com.pharmacy.pharmacymanagementsystem.model.Medicine;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author HP
 */
public class BillingPanel extends javax.swing.JPanel {
    
    private final MedicineDAO medicineDAO = new MedicineDAO();
    private List<Medicine> medicines;
    
    private final BillingDAO billingDAO = new BillingDAO();

    private final List<SaleItem> billItems = new ArrayList<>();

    /**
     * Creates new form BillingPanel
     */
    public BillingPanel() {
        initComponents();
        loadMedicines();
    }
    
    private void loadMedicines() {

    medicines = medicineDAO.getAllMedicines();

    cmbMedicine.removeAllItems();

    cmbMedicine.addItem("Select Medicine");

    for (Medicine medicine : medicines) {

        cmbMedicine.addItem(medicine.getMedicineName());
    }
}
    private void showMedicineDetails() {

    int selectedIndex = cmbMedicine.getSelectedIndex();

    // Index 0 is "Select Medicine"
    if (selectedIndex <= 0) {

        txtAvailable.setText("");
        txtPrice.setText("");

        return;
    }

    Medicine selectedMedicine = medicines.get(selectedIndex - 1);

    txtAvailable.setText(
            String.valueOf(selectedMedicine.getQuantity())
    );

    txtPrice.setText(
            String.valueOf(selectedMedicine.getPrice())
    );
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlBilling = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        lblSubtitle = new javax.swing.JLabel();
        lblCustomerName = new javax.swing.JLabel();
        txtCustomerName = new javax.swing.JTextField();
        lblMedicine = new javax.swing.JLabel();
        cmbMedicine = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        txtAvailable = new javax.swing.JTextField();
        lblPrice = new javax.swing.JLabel();
        txtPrice = new javax.swing.JTextField();
        lblQuantity = new javax.swing.JLabel();
        txtQuantity = new javax.swing.JTextField();
        btnAddToBill = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        lblBillDetails = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableBill = new javax.swing.JTable();
        lblGrandTotal = new javax.swing.JLabel();
        txtGrandTotal = new javax.swing.JTextField();
        btnGenerateBill = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 204, 204));

        pnlBilling.setBackground(new java.awt.Color(255, 255, 255));

        lblTitle.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(44, 62, 80));
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Billing Management");

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));

        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));

        lblSubtitle.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblSubtitle.setForeground(new java.awt.Color(108, 117, 125));
        lblSubtitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSubtitle.setText("Create & Manage Customer Bills");

        lblCustomerName.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblCustomerName.setForeground(new java.awt.Color(44, 62, 80));
        lblCustomerName.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblCustomerName.setText("Customer Name :");

        txtCustomerName.setForeground(new java.awt.Color(33, 37, 41));

        lblMedicine.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblMedicine.setForeground(new java.awt.Color(44, 62, 80));
        lblMedicine.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblMedicine.setText("Medicine :");

        cmbMedicine.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cmbMedicine.setForeground(new java.awt.Color(33, 37, 41));
        cmbMedicine.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Medicine " }));
        cmbMedicine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbMedicineActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(44, 62, 80));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("Available :");

        txtAvailable.setEditable(false);
        txtAvailable.setBackground(new java.awt.Color(233, 236, 239));
        txtAvailable.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtAvailable.setForeground(new java.awt.Color(73, 80, 87));

        lblPrice.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblPrice.setForeground(new java.awt.Color(44, 62, 80));
        lblPrice.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblPrice.setText("Price :");

        txtPrice.setEditable(false);
        txtPrice.setBackground(new java.awt.Color(233, 236, 239));
        txtPrice.setForeground(new java.awt.Color(73, 80, 87));

        lblQuantity.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblQuantity.setForeground(new java.awt.Color(44, 62, 80));
        lblQuantity.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblQuantity.setText("Quantity :");

        txtQuantity.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtQuantity.setForeground(new java.awt.Color(33, 37, 41));

        btnAddToBill.setBackground(new java.awt.Color(40, 167, 69));
        btnAddToBill.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAddToBill.setForeground(new java.awt.Color(255, 255, 255));
        btnAddToBill.setText("Add to Bill");
        btnAddToBill.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAddToBill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddToBillActionPerformed(evt);
            }
        });

        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));

        lblBillDetails.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        lblBillDetails.setForeground(new java.awt.Color(44, 62, 80));
        lblBillDetails.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBillDetails.setText("Bill Details");

        jTableBill.setForeground(new java.awt.Color(33, 37, 41));
        jTableBill.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Medicine", "Quantity", "Price", "Total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Double.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTableBill.setGridColor(new java.awt.Color(222, 226, 230));
        jScrollPane1.setViewportView(jTableBill);

        lblGrandTotal.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        lblGrandTotal.setForeground(new java.awt.Color(44, 62, 80));
        lblGrandTotal.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblGrandTotal.setText("Grand Total :");

        txtGrandTotal.setEditable(false);
        txtGrandTotal.setBackground(new java.awt.Color(248, 249, 250));
        txtGrandTotal.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtGrandTotal.setForeground(new java.awt.Color(44, 62, 80));
        txtGrandTotal.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtGrandTotal.setText("₹0.00");

        btnGenerateBill.setBackground(new java.awt.Color(0, 123, 255));
        btnGenerateBill.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnGenerateBill.setForeground(new java.awt.Color(255, 255, 255));
        btnGenerateBill.setText("Generate Bill");
        btnGenerateBill.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGenerateBill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerateBillActionPerformed(evt);
            }
        });

        btnClear.setBackground(new java.awt.Color(108, 117, 125));
        btnClear.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnClear.setForeground(new java.awt.Color(255, 255, 255));
        btnClear.setText("Clear");
        btnClear.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlBillingLayout = new javax.swing.GroupLayout(pnlBilling);
        pnlBilling.setLayout(pnlBillingLayout);
        pnlBillingLayout.setHorizontalGroup(
            pnlBillingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jSeparator3)
            .addGroup(pnlBillingLayout.createSequentialGroup()
                .addGroup(pnlBillingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlBillingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(pnlBillingLayout.createSequentialGroup()
                            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblGrandTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtGrandTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(6, 6, 6))
                        .addGroup(pnlBillingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlBillingLayout.createSequentialGroup()
                                .addGap(592, 592, 592)
                                .addGroup(pnlBillingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 298, Short.MAX_VALUE)
                                    .addComponent(lblSubtitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(pnlBillingLayout.createSequentialGroup()
                                .addGroup(pnlBillingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnlBillingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(pnlBillingLayout.createSequentialGroup()
                                            .addGap(475, 475, 475)
                                            .addComponent(lblCustomerName, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBillingLayout.createSequentialGroup()
                                            .addContainerGap()
                                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBillingLayout.createSequentialGroup()
                                        .addContainerGap()
                                        .addGroup(pnlBillingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblMedicine, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblQuantity, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblPrice, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(18, 18, 18)
                                .addGroup(pnlBillingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(pnlBillingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtCustomerName)
                                        .addComponent(cmbMedicine, 0, 262, Short.MAX_VALUE)
                                        .addComponent(txtAvailable)
                                        .addComponent(txtPrice))))
                            .addGroup(pnlBillingLayout.createSequentialGroup()
                                .addGap(595, 595, 595)
                                .addComponent(btnAddToBill, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlBillingLayout.createSequentialGroup()
                                .addGap(442, 442, 442)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 557, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(pnlBillingLayout.createSequentialGroup()
                        .addGap(553, 553, 553)
                        .addComponent(btnGenerateBill, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(87, 87, 87)
                        .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlBillingLayout.createSequentialGroup()
                        .addGap(620, 620, 620)
                        .addComponent(lblBillDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(502, Short.MAX_VALUE))
        );
        pnlBillingLayout.setVerticalGroup(
            pnlBillingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBillingLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblSubtitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pnlBillingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCustomerName, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCustomerName, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlBillingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMedicine, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbMedicine, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlBillingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAvailable, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlBillingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlBillingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnAddToBill, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblBillDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(pnlBillingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblGrandTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtGrandTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlBillingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGenerateBill, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(228, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBilling, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlBilling, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cmbMedicineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbMedicineActionPerformed
        // TODO add your handling code here:
        showMedicineDetails();
    }//GEN-LAST:event_cmbMedicineActionPerformed

    private void btnAddToBillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddToBillActionPerformed
        // TODO add your handling code here:
        int selectedIndex = cmbMedicine.getSelectedIndex();

    if (selectedIndex <= 0) {

        JOptionPane.showMessageDialog(
                this,
                "Please select a medicine!"
        );

        return;
    }

    String quantityText = txtQuantity.getText().trim();

    if (quantityText.isEmpty()) {

        JOptionPane.showMessageDialog(
                this,
                "Please enter quantity!"
        );

        return;
    }

    int quantity;

    try {

        quantity = Integer.parseInt(quantityText);

    } catch (NumberFormatException e) {

        JOptionPane.showMessageDialog(
                this,
                "Please enter a valid quantity!"
        );

        return;
    }

    Medicine selectedMedicine =
            medicines.get(selectedIndex - 1);

    int availableQuantity =
            selectedMedicine.getQuantity();

    double price =
            selectedMedicine.getPrice();

    if (quantity <= 0) {

        JOptionPane.showMessageDialog(
                this,
                "Quantity must be greater than zero!"
        );

        return;
    }

    if (quantity > availableQuantity) {

        JOptionPane.showMessageDialog(
                this,
                "Insufficient stock! Available quantity: "
                + availableQuantity
        );

        return;
    }

    /*
     * Create SaleItem
     */
    SaleItem saleItem = new SaleItem(
            selectedMedicine.getId(),
            selectedMedicine.getMedicineName(),
            quantity,
            price
    );

    /*
     * Add SaleItem to list
     */
    billItems.add(saleItem);

    /*
     * Add item to JTable
     */
    DefaultTableModel model =
            (DefaultTableModel) jTableBill.getModel();

    model.addRow(new Object[]{

        selectedMedicine.getMedicineName(),
        quantity,
        price,
        saleItem.getTotal()

    });

    /*
     * Calculate Grand Total
     */
    calculateGrandTotal();

    txtQuantity.setText("");
    }//GEN-LAST:event_btnAddToBillActionPerformed

    private void btnGenerateBillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerateBillActionPerformed
        // TODO add your handling code here:
     String customerName =
            txtCustomerName.getText().trim();

    if (customerName.isEmpty()) {

        JOptionPane.showMessageDialog(
                this,
                "Please enter customer name!"
        );

        return;
    }

    if (billItems.isEmpty()) {

        JOptionPane.showMessageDialog(
                this,
                "Please add at least one medicine to the bill!"
        );

        return;
    }

    double grandTotal = 0;

    for (SaleItem item : billItems) {

        grandTotal += item.getTotal();
    }

    Sale sale = new Sale(
            customerName,
            grandTotal
    );

    boolean success =
            billingDAO.completeSale(
                    sale,
                    billItems
            );

    if (success) {

        JOptionPane.showMessageDialog(
                this,
                "Bill generated successfully!"
        );

        clearBilling();

        /*
         * Reload medicines because stock has changed
         */
        loadMedicines();

    } else {

        JOptionPane.showMessageDialog(
                this,
                "Failed to generate bill!"
        );
    }
    }//GEN-LAST:event_btnGenerateBillActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
        clearBilling();
    }//GEN-LAST:event_btnClearActionPerformed
private void calculateGrandTotal() {

    DefaultTableModel model =
            (DefaultTableModel) jTableBill.getModel();

    double grandTotal = 0;

    for (int i = 0; i < model.getRowCount(); i++) {

        double total =
                Double.parseDouble(
                        model.getValueAt(i, 3).toString()
                );

        grandTotal += total;
    }

    txtGrandTotal.setText(
            String.format("₹%.2f", grandTotal)
    );
}
private void clearBilling() {

    txtCustomerName.setText("");

    cmbMedicine.setSelectedIndex(0);

    txtAvailable.setText("");

    txtPrice.setText("");

    txtQuantity.setText("");

    txtGrandTotal.setText("₹0.00");

    billItems.clear();

    DefaultTableModel model =
            (DefaultTableModel) jTableBill.getModel();

    model.setRowCount(0);
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddToBill;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnGenerateBill;
    private javax.swing.JComboBox<String> cmbMedicine;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTable jTableBill;
    private javax.swing.JLabel lblBillDetails;
    private javax.swing.JLabel lblCustomerName;
    private javax.swing.JLabel lblGrandTotal;
    private javax.swing.JLabel lblMedicine;
    private javax.swing.JLabel lblPrice;
    private javax.swing.JLabel lblQuantity;
    private javax.swing.JLabel lblSubtitle;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JPanel pnlBilling;
    private javax.swing.JTextField txtAvailable;
    private javax.swing.JTextField txtCustomerName;
    private javax.swing.JTextField txtGrandTotal;
    private javax.swing.JTextField txtPrice;
    private javax.swing.JTextField txtQuantity;
    // End of variables declaration//GEN-END:variables
}
