/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.pharmacy.pharmacymanagementsystem.view;

import com.pharmacy.pharmacymanagementsystem.dao.DashboardDAO;

/**
 *
 * @author HP
 */
public class DashboardPanel extends javax.swing.JPanel {
    
    private final DashboardDAO dashboardDAO = new DashboardDAO();

    /**
     * Creates new form DashboardPanel
     */
    public DashboardPanel() {
        initComponents();
        loadDashboardData();
    }

   private void loadDashboardData() {

    // Total Medicines
    int medicineCount =
            dashboardDAO.getTotalMedicines();

    lblMedicineCount.setText(
            String.valueOf(medicineCount)
    );


    // Total Customers
    int customerCount =
            dashboardDAO.getTotalCustomers();

    lblCustomerCount.setText(
            String.valueOf(customerCount)
    );


    // Total Bills
    int billCount =
            dashboardDAO.getTotalBills();

    lblBillsCount.setText(
            String.valueOf(billCount)
    );


    // Total Sales
    double totalSales =
            dashboardDAO.getTotalSales();

    lblSalesAmount.setText(
            String.format("₹%.2f", totalSales)
    );
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlDashboard = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        pnlMedicine = new javax.swing.JPanel();
        lblMedicineTitle = new javax.swing.JLabel();
        lblMedicineCount = new javax.swing.JLabel();
        pnlBills = new javax.swing.JPanel();
        lblBillsTitle = new javax.swing.JLabel();
        lblBillsCount = new javax.swing.JLabel();
        pnlSales = new javax.swing.JPanel();
        lblSalesTitle = new javax.swing.JLabel();
        lblSalesAmount = new javax.swing.JLabel();
        pnlCustomer = new javax.swing.JPanel();
        lblCustomerTitle = new javax.swing.JLabel();
        lblCustomerCount = new javax.swing.JLabel();
        btnRefresh = new javax.swing.JButton();

        pnlDashboard.setBackground(new java.awt.Color(245, 247, 250));

        lblTitle.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(52, 73, 94));
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTitle.setText("Dashboard");

        pnlMedicine.setBackground(new java.awt.Color(255, 255, 255));
        pnlMedicine.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(210, 220, 230)));

        lblMedicineTitle.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblMedicineTitle.setForeground(new java.awt.Color(52, 73, 94));
        lblMedicineTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMedicineTitle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-medicine-32.png"))); // NOI18N
        lblMedicineTitle.setText("Total Medicines");
        lblMedicineTitle.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        lblMedicineCount.setFont(new java.awt.Font("Segoe UI", 1, 34)); // NOI18N
        lblMedicineCount.setForeground(new java.awt.Color(44, 62, 80));
        lblMedicineCount.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMedicineCount.setText("0");

        javax.swing.GroupLayout pnlMedicineLayout = new javax.swing.GroupLayout(pnlMedicine);
        pnlMedicine.setLayout(pnlMedicineLayout);
        pnlMedicineLayout.setHorizontalGroup(
            pnlMedicineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMedicineLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(lblMedicineTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMedicineLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblMedicineCount, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(78, 78, 78))
        );
        pnlMedicineLayout.setVerticalGroup(
            pnlMedicineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMedicineLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(lblMedicineTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(lblMedicineCount, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlBills.setBackground(new java.awt.Color(255, 255, 255));
        pnlBills.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(210, 220, 230)));

        lblBillsTitle.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblBillsTitle.setForeground(new java.awt.Color(52, 73, 94));
        lblBillsTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBillsTitle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-financial-report-32.png"))); // NOI18N
        lblBillsTitle.setText("Total Bills");

        lblBillsCount.setFont(new java.awt.Font("Segoe UI", 1, 34)); // NOI18N
        lblBillsCount.setForeground(new java.awt.Color(44, 62, 80));
        lblBillsCount.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBillsCount.setText("0");

        javax.swing.GroupLayout pnlBillsLayout = new javax.swing.GroupLayout(pnlBills);
        pnlBills.setLayout(pnlBillsLayout);
        pnlBillsLayout.setHorizontalGroup(
            pnlBillsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBillsLayout.createSequentialGroup()
                .addGroup(pnlBillsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlBillsLayout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(lblBillsTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBillsLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblBillsCount, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(64, Short.MAX_VALUE))
        );
        pnlBillsLayout.setVerticalGroup(
            pnlBillsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBillsLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblBillsTitle)
                .addGap(6, 6, 6)
                .addComponent(lblBillsCount, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(55, Short.MAX_VALUE))
        );

        pnlSales.setBackground(new java.awt.Color(255, 255, 255));
        pnlSales.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(210, 220, 230)));

        lblSalesTitle.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblSalesTitle.setForeground(new java.awt.Color(52, 73, 94));
        lblSalesTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSalesTitle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-bar-chart-32.png"))); // NOI18N
        lblSalesTitle.setText("Total Sales");
        lblSalesTitle.setToolTipText("");

        lblSalesAmount.setFont(new java.awt.Font("Segoe UI", 1, 34)); // NOI18N
        lblSalesAmount.setForeground(new java.awt.Color(44, 62, 80));
        lblSalesAmount.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSalesAmount.setText("₹0");

        javax.swing.GroupLayout pnlSalesLayout = new javax.swing.GroupLayout(pnlSales);
        pnlSales.setLayout(pnlSalesLayout);
        pnlSalesLayout.setHorizontalGroup(
            pnlSalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlSalesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlSalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblSalesAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSalesTitle))
                .addGap(65, 65, 65))
        );
        pnlSalesLayout.setVerticalGroup(
            pnlSalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSalesLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblSalesTitle)
                .addGap(18, 18, 18)
                .addComponent(lblSalesAmount)
                .addContainerGap(62, Short.MAX_VALUE))
        );

        pnlCustomer.setBackground(new java.awt.Color(255, 255, 255));
        pnlCustomer.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(210, 220, 230)));

        lblCustomerTitle.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblCustomerTitle.setForeground(new java.awt.Color(52, 73, 94));
        lblCustomerTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCustomerTitle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-customer-32.png"))); // NOI18N
        lblCustomerTitle.setText("Total Customers");

        lblCustomerCount.setFont(new java.awt.Font("Segoe UI", 1, 34)); // NOI18N
        lblCustomerCount.setForeground(new java.awt.Color(44, 62, 80));
        lblCustomerCount.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCustomerCount.setText("0");

        javax.swing.GroupLayout pnlCustomerLayout = new javax.swing.GroupLayout(pnlCustomer);
        pnlCustomer.setLayout(pnlCustomerLayout);
        pnlCustomerLayout.setHorizontalGroup(
            pnlCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCustomerLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(lblCustomerTitle)
                .addContainerGap(60, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlCustomerLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblCustomerCount, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(82, 82, 82))
        );
        pnlCustomerLayout.setVerticalGroup(
            pnlCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCustomerLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lblCustomerTitle)
                .addGap(18, 18, 18)
                .addComponent(lblCustomerCount)
                .addContainerGap(60, Short.MAX_VALUE))
        );

        btnRefresh.setBackground(new java.awt.Color(0, 123, 255));
        btnRefresh.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnRefresh.setForeground(new java.awt.Color(255, 255, 255));
        btnRefresh.setText("Refresh");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlDashboardLayout = new javax.swing.GroupLayout(pnlDashboard);
        pnlDashboard.setLayout(pnlDashboardLayout);
        pnlDashboardLayout.setHorizontalGroup(
            pnlDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDashboardLayout.createSequentialGroup()
                .addGroup(pnlDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlDashboardLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlDashboardLayout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addGroup(pnlDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pnlBills, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pnlMedicine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(64, 64, 64)
                        .addGroup(pnlDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(pnlCustomer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pnlSales, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(pnlDashboardLayout.createSequentialGroup()
                        .addGap(395, 395, 395)
                        .addComponent(btnRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(113, Short.MAX_VALUE))
        );
        pnlDashboardLayout.setVerticalGroup(
            pnlDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDashboardLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69)
                .addGroup(pnlDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlCustomer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlMedicine, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(79, 79, 79)
                .addGroup(pnlDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlBills, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlSales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(btnRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlDashboard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlDashboard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        // TODO add your handling code here:
        loadDashboardData();
    }//GEN-LAST:event_btnRefreshActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRefresh;
    private javax.swing.JLabel lblBillsCount;
    private javax.swing.JLabel lblBillsTitle;
    private javax.swing.JLabel lblCustomerCount;
    private javax.swing.JLabel lblCustomerTitle;
    private javax.swing.JLabel lblMedicineCount;
    private javax.swing.JLabel lblMedicineTitle;
    private javax.swing.JLabel lblSalesAmount;
    private javax.swing.JLabel lblSalesTitle;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JPanel pnlBills;
    private javax.swing.JPanel pnlCustomer;
    private javax.swing.JPanel pnlDashboard;
    private javax.swing.JPanel pnlMedicine;
    private javax.swing.JPanel pnlSales;
    // End of variables declaration//GEN-END:variables
}
