/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.pharmacy.pharmacymanagementsystem.view;

import com.pharmacy.pharmacymanagementsystem.dao.MedicineDAO;
import com.pharmacy.pharmacymanagementsystem.model.Medicine;
import javax.swing.JOptionPane;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author HP
 */
public class MedicinePanel extends javax.swing.JPanel {
    
    private int selectedMedicineId = -1;

    /**
     * Creates new form MedicinePanel
     */
    public MedicinePanel() {
        initComponents();
        
        loadMedicines();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlMedicineForm = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        lblMedicineName = new javax.swing.JLabel();
        txtMedicineName = new javax.swing.JTextField();
        lblCategory = new javax.swing.JLabel();
        txtCategory = new javax.swing.JTextField();
        lblQuantity = new javax.swing.JLabel();
        txtQuantity = new javax.swing.JTextField();
        lblPrice = new javax.swing.JLabel();
        txtPrice = new javax.swing.JTextField();
        lblExpiryDate = new javax.swing.JLabel();
        txtExpiryDate = new javax.swing.JTextField();
        btnButton = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnDelete = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        pnlMedicineForm.setBackground(new java.awt.Color(255, 255, 255));

        lblTitle.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(44, 62, 80));
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTitle.setText("Medicine Management");

        lblMedicineName.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblMedicineName.setForeground(new java.awt.Color(44, 62, 80));
        lblMedicineName.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblMedicineName.setText("Medicine Name");

        txtMedicineName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        lblCategory.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblCategory.setForeground(new java.awt.Color(44, 62, 80));
        lblCategory.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblCategory.setText("Category");

        txtCategory.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        lblQuantity.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblQuantity.setForeground(new java.awt.Color(44, 62, 80));
        lblQuantity.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblQuantity.setText("Quantity");

        txtQuantity.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        lblPrice.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblPrice.setForeground(new java.awt.Color(44, 62, 80));
        lblPrice.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblPrice.setText("Price");

        txtPrice.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        lblExpiryDate.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblExpiryDate.setForeground(new java.awt.Color(44, 62, 80));
        lblExpiryDate.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblExpiryDate.setText("Expiry Date");

        txtExpiryDate.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtExpiryDate.setText("YYYY-MM-DD");

        btnButton.setBackground(new java.awt.Color(40, 167, 69));
        btnButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnButton.setForeground(new java.awt.Color(255, 255, 255));
        btnButton.setText("Add Medicine");
        btnButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnButtonActionPerformed(evt);
            }
        });

        btnClear.setBackground(new java.awt.Color(108, 117, 125));
        btnClear.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnClear.setForeground(new java.awt.Color(255, 255, 255));
        btnClear.setText("Clear");
        btnClear.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Medicine Name", "Category", "Quantity", "Price", "Expiry Date"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Double.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        btnDelete.setBackground(new java.awt.Color(220, 53, 69));
        btnDelete.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnDelete.setForeground(new java.awt.Color(255, 255, 255));
        btnDelete.setText("Delete");
        btnDelete.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnUpdate.setBackground(new java.awt.Color(0, 123, 255));
        btnUpdate.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnUpdate.setForeground(new java.awt.Color(255, 255, 255));
        btnUpdate.setText("Update");
        btnUpdate.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(44, 62, 80));
        jLabel1.setText("Medicine Table");

        javax.swing.GroupLayout pnlMedicineFormLayout = new javax.swing.GroupLayout(pnlMedicineForm);
        pnlMedicineForm.setLayout(pnlMedicineFormLayout);
        pnlMedicineFormLayout.setHorizontalGroup(
            pnlMedicineFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMedicineFormLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(pnlMedicineFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlMedicineFormLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(pnlMedicineFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblExpiryDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblPrice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblCategory, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblMedicineName, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                            .addComponent(lblQuantity, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(39, 39, 39)
                        .addGroup(pnlMedicineFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtMedicineName)
                            .addComponent(txtCategory)
                            .addComponent(txtQuantity)
                            .addComponent(txtPrice)
                            .addComponent(txtExpiryDate)
                            .addGroup(pnlMedicineFormLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(pnlMedicineFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnUpdate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(42, 42, 42)
                                .addGroup(pnlMedicineFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnClear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnDelete, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)))))
                    .addComponent(lblTitle))
                .addGap(117, 117, 117)
                .addGroup(pnlMedicineFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 557, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(188, Short.MAX_VALUE))
        );
        pnlMedicineFormLayout.setVerticalGroup(
            pnlMedicineFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMedicineFormLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(pnlMedicineFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60)
                .addGroup(pnlMedicineFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnlMedicineFormLayout.createSequentialGroup()
                        .addGroup(pnlMedicineFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtMedicineName, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblMedicineName, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(pnlMedicineFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(pnlMedicineFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnlMedicineFormLayout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(lblQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(29, 29, 29)
                        .addGroup(pnlMedicineFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(pnlMedicineFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblExpiryDate, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtExpiryDate, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(57, 57, 57)
                        .addGroup(pnlMedicineFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(32, 32, 32)
                .addGroup(pnlMedicineFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(132, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(pnlMedicineForm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlMedicineForm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnButtonActionPerformed

        String medicineName = txtMedicineName.getText().trim();
        String category = txtCategory.getText().trim();
        String quantityText = txtQuantity.getText().trim();
        String priceText = txtPrice.getText().trim();
        String expiryDate = txtExpiryDate.getText().trim();
        
        if (medicineName.isEmpty() || category.isEmpty()|| quantityText.isEmpty() || priceText.isEmpty()|| expiryDate.isEmpty()) {
            JOptionPane.showMessageDialog(this,"Please fill all fields!");
            return;
        
        }
        try {
            int quantity = Integer.parseInt(quantityText);
            double price = Double.parseDouble(priceText);
            
            Medicine medicine = new Medicine(medicineName,category,quantity,price,expiryDate);
            MedicineDAO dao = new MedicineDAO();
            
            if (dao.addMedicine(medicine)) {
                
                JOptionPane.showMessageDialog(this,"Medicine added successfully!");
                clearFields();
                
                //resfresh JTable
                loadMedicines();
            
            } else {
                JOptionPane.showMessageDialog(this,"Failed to add medicine!");
            }
        
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this,"Quantity must be a whole number and Price must be a number!");
            }
    }//GEN-LAST:event_btnButtonActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
        clearFields();
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        int selectedRow = jTable1.getSelectedRow();

    if (selectedRow == -1) {
        JOptionPane.showMessageDialog(
                this,
                "Please select a medicine to delete."
        );
        return;
    }

    int id = (int) jTable1.getValueAt(selectedRow, 0);

    int confirmation = JOptionPane.showConfirmDialog(
            this,
            "Are you sure you want to delete this medicine?",
            "Confirm Delete",
            JOptionPane.YES_NO_OPTION
    );

    if (confirmation == JOptionPane.YES_OPTION) {

        MedicineDAO dao = new MedicineDAO();

        if (dao.deleteMedicine(id)) {

            JOptionPane.showMessageDialog(
                    this,
                    "Medicine deleted successfully!"
            );

            loadMedicines();
            clearFields();

        } else {

            JOptionPane.showMessageDialog(
                    this,
                    "Failed to delete medicine."
            );
        }
    }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        int selectedRow = jTable1.getSelectedRow();

    if (selectedRow != -1) {

        selectedMedicineId = (int) jTable1.getValueAt(selectedRow, 0);

        txtMedicineName.setText(
                jTable1.getValueAt(selectedRow, 1).toString()
        );

        txtCategory.setText(
                jTable1.getValueAt(selectedRow, 2).toString()
        );

        txtQuantity.setText(
                jTable1.getValueAt(selectedRow, 3).toString()
        );

        txtPrice.setText(
                jTable1.getValueAt(selectedRow, 4).toString()
        );

        txtExpiryDate.setText(
                jTable1.getValueAt(selectedRow, 5).toString()
        );
    }
    }//GEN-LAST:event_jTable1MouseClicked

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        if (selectedMedicineId == -1) {
        JOptionPane.showMessageDialog(
                this,
                "Please select a medicine to update."
        );
        return;
    }

    try {

        String medicineName = txtMedicineName.getText().trim();
        String category = txtCategory.getText().trim();
        int quantity = Integer.parseInt(txtQuantity.getText().trim());
        double price = Double.parseDouble(txtPrice.getText().trim());
        String expiryDate = txtExpiryDate.getText().trim();

        Medicine medicine = new Medicine(
                selectedMedicineId,
                medicineName,
                category,
                quantity,
                price,
                expiryDate
        );

        MedicineDAO dao = new MedicineDAO();

        if (dao.updateMedicine(medicine)) {

            JOptionPane.showMessageDialog(
                    this,
                    "Medicine updated successfully!"
            );

            loadMedicines();
            clearFields();
            selectedMedicineId = -1;

        } else {

            JOptionPane.showMessageDialog(
                    this,
                    "Failed to update medicine."
            );
        }

    } catch (NumberFormatException e) {

        JOptionPane.showMessageDialog(
                this,
                "Quantity must be a whole number and Price must be a number!"
        );
    }
    }//GEN-LAST:event_btnUpdateActionPerformed
private void clearFields() {

    txtMedicineName.setText("");
    txtCategory.setText("");
    txtQuantity.setText("");
    txtPrice.setText("");
    txtExpiryDate.setText("");

}
private void loadMedicines() {

    MedicineDAO dao = new MedicineDAO();

    List<Medicine> medicines = dao.getAllMedicines();

    DefaultTableModel model =
            (DefaultTableModel) jTable1.getModel();

    model.setRowCount(0);

    for (Medicine medicine : medicines) {

        model.addRow(new Object[]{
            medicine.getId(),
            medicine.getMedicineName(),
            medicine.getCategory(),
            medicine.getQuantity(),
            medicine.getPrice(),
            medicine.getExpiryDate()
        });
    }
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnButton;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblCategory;
    private javax.swing.JLabel lblExpiryDate;
    private javax.swing.JLabel lblMedicineName;
    private javax.swing.JLabel lblPrice;
    private javax.swing.JLabel lblQuantity;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JPanel pnlMedicineForm;
    private javax.swing.JTextField txtCategory;
    private javax.swing.JTextField txtExpiryDate;
    private javax.swing.JTextField txtMedicineName;
    private javax.swing.JTextField txtPrice;
    private javax.swing.JTextField txtQuantity;
    // End of variables declaration//GEN-END:variables
}
